### ISSUE TITLE
About CUfunctions

### ISSUE THREAD

**Issue by Yunze543** [unal-optodigital/JDiffraction#2]
This library is very helpful, but I can't get the CUfunctions when I tried to use the GPU. Could you please provide the cu files as well? Thanks a lot

**Comment by piedrahitapablo** [comment]
Hi @Yunze543 I'm sorry for the late response, I have been very busy with other things, let me know if you still need the cu files.

**Comment by Yunze543** [comment]
Thanks! I had found the files on ScienceDirect, i didn't notice this before.
